version: '3.5'

services:

  elasticsearch:
    image: ${REGISTRY_ADDRESS}elasticsearch-ems
    build: 
      context: ./images/elasticsearch-ems
    hostname: elasticsearch
    depends_on:
      - db
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
# --- For docker-compose (without Swarm mode) ----
#      - bootstrap.memory_lock=true
      - cluster.name=LiferayElasticsearchCluster
      - network.host=0.0.0.0
      - network.publish_host=elasticsearch
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./configs/elasticsearch-ems/synonyms.txt:/usr/share/elasticsearch/config/analysis/synonyms.txt:ro
    ports:
      - 9200:9200
      - 9300:9300
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - backend-network

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend-network
    environment:
      MYSQL_USER: lportal
      MYSQL_ROOT_PASSWORD: Sully000!
      MYSQL_PASSWORD: Sully000!
      MYSQL_DATABASE: ems-v3_51_2-anonym

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
    networks:
      - backend-network

  liferay-active:
    image: ${REGISTRY_ADDRESS}liferay-ems:${LFR_TAG_VERSION}
    build : 
      context: ./images/liferay-ems
      args:
        - DIST_PATH_VERSION=${LFR_TAG_VERSION}
    environment:
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DB}?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true&serverTimezone=Europe/Paris
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=${MYSQL_USER}
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=${MYSQL_PASSWORD}
      - LIFERAY_LIFERAY_PERIOD_HOME=/opt/liferay
      - LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_AUTH=false
      - LIFERAY_MAIL_PERIOD_AUDIT_PERIOD_TRAIL=${TRAIL_MAIL_ADDRESS}
      - LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_ADDRESS=test@liferay.com
      - LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_NAME=Admin Liferay
      # Cluster configuration
      #- LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED=true
      #- LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_CHANNEL_PERIOD_PROPERTIES_PERIOD_CONTROL=/opt/liferay/jdbc_ping.xml
      #- LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_CHANNEL_PERIOD_PROPERTIES_PERIOD_TRANSPORT_PERIOD__NUMBER0_=/opt/liferay/jdbc_ping.xml
      #- LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_AUTODETECT_PERIOD_ADDRESS=www.google.com:80
    volumes:
      -  ./configs/liferay-ems-active/files:/mnt/liferay/files
      -  ./configs/liferay-ems-active/deploy:/mnt/liferay/deploy
      -  ./configs/liferay-ems-active/patching:/mnt/liferay/patching
      -  ./configs/liferay-ems-active/scripts:/mnt/liferay/scripts
    ports:
      - 8080:8080
      - 8009:8009
    hostname: ${LCS_LIFERAY_ACTIVE_HOSTNAME}
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - backend-network


networks:

  backend-network:
    name: backend-network